/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: ['selector', ':root[data-theme="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        display: ['var(--font-display)'],
        body: ['var(--font-body)'],
        sans: ['var(--font-body)'],
      },
      colors: {
        surface: {
          0: 'var(--surface-0)',
          1: 'var(--surface-1)',
          2: 'var(--surface-2)',
          3: 'var(--surface-3)',
          4: 'var(--surface-4)',
          card: 'var(--surface-card)',
          elevated: 'var(--surface-card-elevated)',
          glass: 'var(--surface-glass)',
          'glass-strong': 'var(--surface-glass-strong)',
          'glass-subtle': 'var(--surface-glass-subtle)',
        },
        line: {
          soft: 'var(--line-soft)',
          medium: 'var(--line-medium)',
          strong: 'var(--line-strong)',
        },
        ink: {
          strong: 'var(--ink-strong)',
          medium: 'var(--ink-medium)',
          soft: 'var(--ink-soft)',
          muted: 'var(--ink-muted)',
        },
        brand: {
          primary: 'var(--color-primary)',
          'primary-hover': 'var(--color-primary-hover)',
          'primary-light': 'var(--color-primary-light)',
          secondary: 'var(--color-secondary)',
          'secondary-light': 'var(--color-secondary-light)',
          accent: 'var(--color-accent)',
          'accent-light': 'var(--color-accent-light)',
          cyan: 'var(--color-cyan)',
          teal: 'var(--color-teal)',
          indigo: 'var(--color-indigo)',
          violet: 'var(--color-violet)',
          pink: 'var(--color-pink)',
          success: 'var(--color-success)',
          warning: 'var(--color-warning)',
          error: 'var(--color-error)',
        },
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        glow: 'var(--shadow-glow)',
        card: 'var(--card-shadow)',
      },
      spacing: {
        'ui-1': '8px',
        'ui-2': '16px',
        'ui-3': '24px',
        'ui-4': '32px',
        'ui-5': '40px',
        'ui-6': '48px',
        'ui-8': '64px',
        control: 'var(--control-h)',
        'page-x': 'var(--page-pad-x)',
        'page-y': 'var(--page-pad-y)',
        section: 'var(--section-gap)',
        card: 'var(--card-pad)',
      },
      maxWidth: {
        page: 'var(--page-content-max)',
      },
      screens: {
        shell: '901px',
      },
      keyframes: {
        routeFade: {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        authRouteFade: {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        panelRouteFade: {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        fadePop: {
          from: { opacity: '0', transform: 'translateY(8px) scale(0.97)' },
          to: { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '220% center' },
          '100%': { backgroundPosition: '-220% center' },
        },
        signoutSoftExit: {
          to: { opacity: '0.18', transform: 'translateY(10px)' },
        },
        signoutCurtainIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        signoutSpin: {
          to: { transform: 'rotate(360deg)' },
        },
        orbFloat: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '33%': { transform: 'translate(8px, -12px) scale(1.04)' },
          '66%': { transform: 'translate(-6px, 8px) scale(0.97)' },
        },
        themeMoonHaloPulse: {
          '0%, 100%': { opacity: '0.16', transform: 'scale(0.96)' },
          '50%': { opacity: '0.34', transform: 'scale(1.08)' },
        },
        themeMoonFloat: {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '50%': { transform: 'translateY(-0.8px) rotate(-3deg)' },
        },
        themeNightStarsDrift: {
          '0%, 100%': { opacity: '0.42', transform: 'translate(0, 0) rotate(0deg)' },
          '50%': { opacity: '0.9', transform: 'translate(0.75px, -0.5px) rotate(9deg)' },
        },
        themeNightStarTwinkle: {
          '0%, 100%': { opacity: '0.5', transform: 'scale(0.78)' },
          '48%': { opacity: '1', transform: 'scale(1.12)' },
        },
        themeNightShootingStar: {
          '0%, 58%, 100%': { opacity: '0', transform: 'translate(-1px, 1px)' },
          '66%': { opacity: '0.95', transform: 'translate(0, 0)' },
          '78%': { opacity: '0', transform: 'translate(2.4px, -0.65px)' },
        },
        progressShimmer: {
          '0%': { backgroundPosition: '-100% center', opacity: '0' },
          '20%': { opacity: '1' },
          '80%': { opacity: '1' },
          '100%': { backgroundPosition: '200% center', opacity: '0' },
        },
        wave: {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '20%': { transform: 'rotate(20deg)' },
          '40%': { transform: 'rotate(-8deg)' },
          '60%': { transform: 'rotate(14deg)' },
          '80%': { transform: 'rotate(-4deg)' },
        },
        lpPathTrace: {
          '0%': { strokeDashoffset: 'var(--lp-path-length, 1600)', opacity: '0.35' },
          '8%': { opacity: '1' },
          '72%': { opacity: '1' },
          '100%': { strokeDashoffset: '0', opacity: '0.35' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '.3' },
        },
        lpFloatA: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-9px)' },
        },
        lpFloatB: {
          '0%, 100%': { transform: 'translateY(-5px)' },
          '50%': { transform: 'translateY(5px)' },
        },
        lpPlanGlow: {
          '0%, 100%': { boxShadow: '0 0 0 1px rgba(99,102,241,0.25), 0 16px 48px rgba(37,99,235,0.15)' },
          '50%': { boxShadow: '0 0 0 1px rgba(99,102,241,0.42), 0 20px 60px rgba(37,99,235,0.26), 0 0 36px rgba(99,102,241,0.16)' },
        },
        lpCtaDriftA: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '50%': { transform: 'translate(18px, -14px) scale(1.06)' },
        },
        lpCtaDriftB: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '50%': { transform: 'translate(-14px, 12px) scale(1.04)' },
        },
        qtrBackdropIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        qtrPopupIn: {
          from: { opacity: '0', transform: 'translateY(16px) scale(0.97)' },
          to: { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        qtrPopupSheetIn: {
          from: { opacity: '0', transform: 'translateY(100%)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        hfFloat: {
          '0%, 100%': { transform: 'translateY(0px) rotate(-4deg)' },
          '50%': { transform: 'translateY(-10px) rotate(4deg)' },
        },
        slideUpFade: {
          from: { opacity: '0', transform: 'translateY(14px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        slideDownFade: {
          from: { opacity: '0', transform: 'translateY(-8px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          from: { opacity: '0', transform: 'scale(0.95) translateY(6px)' },
          to:   { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        scaleInFast: {
          from: { opacity: '0', transform: 'scale(0.97)' },
          to:   { opacity: '1', transform: 'scale(1)' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(37, 99, 235, 0.0)' },
          '50%':       { boxShadow: '0 0 0 6px rgba(37, 99, 235, 0.12)' },
        },
        cardFadeIn: {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        toastSlideUp: {
          from: { opacity: '0', transform: 'translateY(12px) scale(0.97)' },
          to:   { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        dropdownIn: {
          from: { opacity: '0', transform: 'translateY(-4px) scale(0.96)' },
          to:   { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        overlayIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        scrollBounce: {
          '0%, 100%': { transform: 'translateY(0)',   opacity: '0.2'  },
          '50%':       { transform: 'translateY(5px)', opacity: '0.45' },
        },
      },
      animation: {
        routeFade: 'routeFade var(--lms-route-enter-duration, 0.24s) var(--lms-route-enter-ease, cubic-bezier(0.16,1,0.3,1)) both',
        authRouteFade: 'authRouteFade var(--lms-route-enter-duration, 0.24s) var(--lms-route-enter-ease, cubic-bezier(0.16,1,0.3,1)) both',
        panelRouteFade: 'panelRouteFade var(--lms-panel-route-duration, 0.24s) var(--lms-panel-route-ease, cubic-bezier(0.16,1,0.3,1)) both',
        fadePop: 'fadePop var(--lms-modal-duration, 0.22s) var(--lms-motion-ease-out, cubic-bezier(0.16,1,0.3,1)) both',
        slideUpFade:   'slideUpFade var(--lms-card-enter-duration, 0.22s) var(--lms-motion-ease-out, cubic-bezier(0.16,1,0.3,1)) both',
        slideDownFade: 'slideDownFade var(--lms-dropdown-duration, 0.18s) var(--lms-motion-ease-out, cubic-bezier(0.16,1,0.3,1)) both',
        scaleIn:     'scaleIn var(--lms-modal-duration, 0.22s) var(--lms-motion-ease-out, cubic-bezier(0.16,1,0.3,1)) both',
        scaleInFast: 'scaleInFast var(--lms-motion-duration-dropdown, 0.16s) var(--lms-motion-ease-out, cubic-bezier(0.16,1,0.3,1)) both',
        pulseGlow:   'pulseGlow 2.4s ease-in-out infinite',
        cardFadeIn:  'cardFadeIn var(--lms-card-enter-duration, 0.22s) var(--lms-motion-ease-out, cubic-bezier(0.16,1,0.3,1)) both',
        toastSlideUp: 'toastSlideUp var(--lms-motion-duration-dropdown, 0.18s) var(--lms-motion-ease-out, cubic-bezier(0.16,1,0.3,1)) both',
        dropdownIn:  'dropdownIn var(--lms-dropdown-duration, 0.18s) var(--ease-out) both',
        overlayIn: 'overlayIn var(--lms-motion-duration-dropdown, 0.18s) var(--ease-out) both',
        shimmer: 'shimmer 1.6s ease-in-out infinite',
        signoutSoftExit: 'signoutSoftExit 0.44s var(--ease-std) forwards',
        signoutCurtainIn: 'signoutCurtainIn 0.3s var(--ease-std) forwards',
        signoutSpin: 'signoutSpin 0.8s linear infinite',
        orbFloat: 'orbFloat 18s ease-in-out infinite',
        orbFloatReverse: 'orbFloat 22s ease-in-out infinite reverse',
        themeMoonHaloPulse: 'themeMoonHaloPulse 2.8s ease-in-out infinite',
        themeMoonFloat: 'themeMoonFloat 3.2s ease-in-out infinite',
        themeNightStarsDrift: 'themeNightStarsDrift 3.8s ease-in-out infinite',
        themeNightStarTwinkle: 'themeNightStarTwinkle 1.9s ease-in-out infinite',
        themeNightStarTwinkleDelay: 'themeNightStarTwinkle 1.9s 0.45s ease-in-out infinite',
        themeNightShootingStar: 'themeNightShootingStar 3.4s ease-in-out infinite',
        progressShimmer: 'progressShimmer 2.2s var(--ease-std) infinite 0.6s',
        wave: 'wave 2s ease-in-out infinite',
        lpPathTrace: 'lpPathTrace 8.6s cubic-bezier(0.45,0,0.2,1) infinite',
        pulseSoft: 'pulseSoft 2s infinite',
        lpFloatA: 'lpFloatA 5.8s 0.3s ease-in-out infinite',
        lpFloatB: 'lpFloatB 6.6s 1s ease-in-out infinite',
        lpPlanGlow: 'lpPlanGlow 3.2s ease-in-out infinite',
        lpCtaDriftA: 'lpCtaDriftA 9s ease-in-out infinite',
        lpCtaDriftB: 'lpCtaDriftB 11s ease-in-out infinite',
        qtrSpin: 'spin 0.9s linear infinite',
        qtrBackdropIn: 'qtrBackdropIn 0.18s ease',
        qtrPopupIn: 'qtrPopupIn 0.22s cubic-bezier(0.34,1.26,0.64,1)',
        qtrPopupSheetIn: 'qtrPopupSheetIn 0.25s cubic-bezier(0.34,1.1,0.64,1)',
        hfFloat: 'hfFloat 6s ease-in-out infinite',
        scrollBounce: 'scrollBounce 1.8s ease-in-out infinite',
      },
    },
  },
};
